name: Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  get-repo-info:
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  # this job is only needed to get the tag of server and telegram-bot-api
  get-img-tag:
    name: Get the image tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Checkout telegram-bot-api repo
        uses: actions/checkout@v3
        with:
          repository: tdlib/telegram-bot-api
          path: telegram-bot-api
          submodules: recursive
      - name: Get the image tag
        run: |
          telegram_bot_api_revision=$(cd telegram-bot-api && git rev-parse --short HEAD)
          tg_server_version=$(cat telegram-bot-api/CMakeLists.txt | grep TelegramBotApi | cut -d " " -f3)
          echo "BUILD_VER=$tg_server_version-$telegram_bot_api_revision" >> $GITHUB_OUTPUT

  build-docker:
    needs:
      - get-repo-info
      - get-img-tag
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            tag: ${{ needs.get-img-tag.outputs.BUILD_VER }}
            latest_image: true
    uses: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      dockerfile: ${{ matrix.dockerfile }}
      tag: ${{ matrix.tag }}
      latest_image: ${{ matrix.latest_image }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  automerge-dependabot-pr:
    needs: build-docker
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
